name: FuelBomb
version: 2.9
main: it.premx.fuelbomb.fuelbomb
author: Premx
softdepend: [WorldGuard]
api-version: 1.13
permissions:
  fuelbomb.use:
    default: true
    description: Ability to throw fuelbomb.
  fuelbomb.reload:
    default: op
    description: Ability to reload config.
  fuelbomb.update:
    default: op
    description: Ability to reload config.
  fuelbomb.give:
    default: op
    description: Allow to use give command
commands:
   fuelbomb:
      description: Commands...
      usage: /<command>
